routes/web.php
<?php

use App\Http\Controllers\FoodController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/food', FoodController::class);

app/Models/Food.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Food extends Model
{
    protected $table = 'foods'; // Specify the table name

    protected $fillable = ['nama', 'harga', 'gambar'];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/FoodController.php
<?php

namespace App\Http\Controllers;

use App\Models\Food;
use Illuminate\Http\Request;

class FoodController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
        $foods = Food::get();

        return view('index', compact('foods'));
        
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
        $foods = Food::get();
        return view('tambah', compact('foods'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        // dd($request);
        //// Validate the request data
        $request->validate([
            'nama' => 'required|string|max:255',
            'harga' => 'required|numeric',
            'gambar' => [ 'file', 'image'],
        ]);

        // Create a new food item

        $request['link_gambar'] = $request->file('gambar')->store('foods_images');
        Food::create([
            'nama' => $request->input('nama'),
            'harga' => $request->input('harga'),
            'gambar' => $request->input('link_gambar'),
        ]);

        return back();
    }

    /**
     * Display the specified resource.
     */
    public function show(Food $food)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        //

        // dd($id);

        $foods = Food::findOrFail($id);

        return view('edit', compact('foods'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, $id)
    {
        //
        $foods = Food::findOrFail($id);
        $foods->update($request->all());


        return redirect()->route('food.create');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Food $food)
    {
        //

        // dd($food->id);
        $fooddelete = Food::findOrFail($food->id);

        // Delete the food item
        $fooddelete->delete();

        return back();
    }
}

resources/views/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.css" rel="stylesheet" >
    <title>Food Menu</title>
   
</head>
<body class="bg-gray-100">

    <div class="container mx-auto py-8">
        <h1 class="text-2xl font-bold mb-4">Update Menu</h1>
        <div class="mb-4 ">
            <form method="POST" action="{{ route('food.update', $foods->id) }}" enctype="multipart/form-data" class="flex">
                @csrf
                @method('PUT')
                <div class="relative mr-2">
                    <input type="text" id="nama" name="nama" class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-1 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-cyan-600 peer" value="{{$foods->nama
                    }}" placeholder=" " />
                    <label for="nama" class="absolute text-sm text-gray-500 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-gray-100 px-2 peer-focus:px-2 peer-focus:text-cyan-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">Nama Makanan</label>
                </div>
                <div class="relative mr-2">
                    <input type="number" id="harga" name="harga" class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-1 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-cyan-600 peer" value="{{$foods->harga
                    }}" placeholder=" " />
                    <label for="harga" class="absolute text-sm text-gray-500 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-gray-100 px-2 peer-focus:px-2 peer-focus:text-cyan-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">Harga</label>
                </div>
                <div class="relative mr-2">
                            
                            
                    {{-- <label class="block mb-2 text-sm font-medium text-gray-900 " for="file_input">Foto</label> --}}
                    <input class="block w-full text-sm text-gray-500 border border-gray-300 rounded-lg cursor-pointer bg-transparent bg-cyan-700" aria-describedby="file_input_help" id="file_input" name="gambar" type="file">
                    {{-- <p class="mt-1 text-sm text-gray-500 " id="file_input_help">SVG, PNG, JPG or GIF (MAX. 800x400px).</p> --}}

                </div>
                <button type="submit" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2">Update</button>
            </form>            
        </div>
    </div>


</body>

<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js"></script>
</html>

resources/views/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.css" rel="stylesheet" >
    <title>Food Menu</title>
   
</head>
<body class="bg-gray-100">
    <div class="container mx-auto py-8">
        <div class="flex">
            <!-- Left side: Food Menu -->
            <div class="w-3/4 p-4">
                <div class="flex">
                    <h1 class="text-2xl font-bold mb-4 mr-4">Food Menu</h1>
                    <h1 class="text-2xl mb-4"><a href="/food/create">Add Menu</a></h1>
                </div>

                <div class="grid grid-cols-4 gap-4">
                    @foreach ($foods as $food)
                    <div class="bg-white p-4 rounded-lg shadow">
                        @php
                        $foodImage = asset('storage/' . $food->gambar);
                        $foodNameInitials = strtoupper(substr($food->nama, 0, 2));
                        @endphp
                        <div class="relative w-full h-40 mb-2">
                            <img src="{{ $foodImage }}" alt="{{ $food->nama }}" class="w-full h-full object-cover rounded" onerror="this.style.display='none'; document.getElementById('foodInitials{{ $food->id }}').style.display='block';">
                            <div id="foodInitials{{ $food->id }}" class="hidden absolute inset-0 flex items-center justify-center text-white font-bold text-3xl bg-black opacity-75">{{ $foodNameInitials }}</div>
                        </div>
                        <p class="text-lg font-semibold">{{ $food->nama }}</p>
                        <p class="text-gray-600">{{ $food->harga }}</p>
                        <button class="mt-2 bg-blue-500 hover:bg-blue-600 text-white py-2 px-4 rounded-full" onclick="addToCart('{{ $food->nama }}', {{ $food->harga }})">Tambah</button>
                    </div>
                    @endforeach
                    
                    
                    
                    
                </div>
            </div>

            <!-- Right side: Bill -->
            <div class="w-2/5 p-4">
                <h1 class="text-2xl font-bold mb-4">Bill</h1>
                <div class="bg-white p-4 rounded-lg shadow">
                    <h3 class="text-2xl font-bold mb-4">New Customer</h3>
                    <!-- Bill items will be dynamically added here -->
                    <p>Dine in</p>
                    <div>
                        <table id="tabelbill" class="w-full text-sm text-left text-gray-900">
                            <thead>

                            </thead>
                            <tbody id="table-body">
                                <!-- Table body will be filled with dummy data using JavaScript -->
                            </tbody>
                        </table>
                    </div>
                    <button class="mt-2 bg-green-500 hover:bg-green-600 text-white py-2 px-4 rounded-full " onclick="clearButtonClick()">Clear</button>
                    <button class="mt-2 bg-green-500 hover:bg-green-600 text-white py-2 px-4 rounded-full">Save Bill</button>
                    <button class="mt-2 bg-green-500 hover:bg-green-600 text-white py-2 px-4 rounded-full" onclick="printTable()">Print Bill</button>

                </div>
                <div class="mt-4">
                    <p id="totalbelanja"class="text-lg font-semibold"></p>
                    <button data-modal-target="small-modal" data-modal-toggle="small-modal" class="mt-2 bg-green-500 hover:bg-green-600 text-white py-2 px-4 rounded-full">Checkout</button>
                </div>

            </div>
        </div>
    </div>



    {{-- Modal --}}
    <!-- Small Modal -->
    <div id="small-modal" tabindex="-1" class="fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
        <div class="relative w-full max-w-md max-h-full">
            <!-- Modal content -->
            <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                <!-- Modal header -->
                <div class="flex items-center justify-between p-5 border-b rounded-t dark:border-gray-600">
                    <h3 class="text-xl font-medium text-gray-900 dark:text-white">
                        Checkout
                    </h3>
                    <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ml-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-hide="small-modal">
                        <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                        </svg>
                        <span class="sr-only">Close modal</span>
                    </button>
                </div>
                <!-- Modal body -->
                <div class="p-6">
                    <p id="totalbelanjamodal" class="text-sm font-medium text-gray-900"></p>
                    <label for="small-input" class="text-sm mr-2 font-medium text-gray-900">Masukkan Nominal Uang</label>
                    <input id="inputField" type="text" class="text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 ">
                    <p class="text-sm font-medium text-gray-900">Kembalian Rp <span id="kembalian">0</span></p>
                    
                </div>
                <!-- Modal footer -->
                <div class="flex items-center p-6 space-x-2 border-t border-gray-200 rounded-b ">
                    <button data-modal-hide="small-modal" type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center ">Selesai</button>
                </div>
            </div>
        </div>
    </div>
</body>




<script>

    function addToCart(itemName, price) {
        const existingItem = dummyData.find((item) => item.name === itemName);
        
        if (existingItem) {
            existingItem.jumlah += 1;
        } else {
            dummyData.push({ name: itemName, price: price, jumlah: 1 });
        }

        updateBillTable();
    }

    let totalPrice = 0; // Initialize the total price
        
    let dummyData = [];
    function updateBillTable() {
        // Get a reference to the table body
        const tableBody = document.getElementById('table-body');

        tableBody.innerHTML = '';

        // Loop through the dummy data and populate the table

        dummyData.forEach((data) => {
            const row = document.createElement('tr');

            // Create table cells for each data point
            const itemCell = document.createElement('td');
            itemCell.textContent = data.name;

            const jumlahCell = document.createElement('td');
            jumlahCell.textContent = data.jumlah;

            const hargaCell = document.createElement('td');
            const totalHarga = data.price * data.jumlah;
            hargaCell.textContent = "Rp. " + totalHarga;
            totalPrice += totalHarga; // Add to the total price

            // Append cells to the row
            row.appendChild(itemCell);
            row.appendChild(jumlahCell);
            row.appendChild(hargaCell);

            // Append the row to the table body
            tableBody.appendChild(row);
        });

        document.getElementById('totalbelanja').innerHTML = "Total Rp." + totalPrice
        document.getElementById('totalbelanjamodal').innerHTML = "Total Belanja Rp." + totalPrice

    }

    function calculateKembalian() {
        // Get references to the input field and the kembalian span element
        const inputField = document.getElementById("inputField");
        const kembalianSpan = document.getElementById("kembalian");

        // Set the total price (you can replace this with your actual total price)
        // Replace with your total price

        // Add an event listener to the input field to calculate kembalian
        inputField.addEventListener("input", () => {
            // Get the user's input value as a number
            const inputValue = parseFloat(inputField.value) || 0;

            // Calculate the kembalian (change)
            const kembalianValue = inputValue - totalPrice;

            // Update the kembalian span with the calculated value
            kembalianSpan.textContent = kembalianValue.toFixed(2); // Display with two decimal places
        });
        }

        // Call the function to initialize the event listener
        calculateKembalian();



    const clearButton = document.getElementById('clear-button');

    // Define a function to perform when the button is clicked
    function clearButtonClick() {
        // Perform the desired action here
        // For example, you can clear the content of a specific element or reset some values
        // Here's an example that clears a <div> with the ID 'result-container'
        const tableBody = document.getElementById('table-body');
    
        tableBody.innerHTML = '';
        dummyData = []
    }


    function printTable() {
        var divToPrint = document.getElementById('tabelbill');
        newWin = window.open("");
        newWin.document.write(divToPrint.outerHTML);
        newWin.print();
        newWin.close();
   }

       
    
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js"></script>
</html>

resources/views/tambah.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.css" rel="stylesheet" >
    <title>Food Menu</title>
   
</head>
<body class="bg-gray-100">

    <div class="container mx-auto py-8">
        <h1 class="text-2xl font-bold mb-4">Food Menu</h1>
        <div class="mb-4 ">
            <form method="POST" action="{{ route('food.store') }}" enctype="multipart/form-data" class="flex">
                @csrf
                
                <div class="relative mr-2">
                    <input type="text" id="nama" name="nama" class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-1 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-cyan-600 peer" placeholder=" " />
                    <label for="nama" class="absolute text-sm text-gray-500 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-gray-100 px-2 peer-focus:px-2 peer-focus:text-cyan-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">Nama Makanan</label>
                </div>
                <div class="relative mr-2">
                    <input type="number" id="harga" name="harga" class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-1 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-cyan-600 peer" placeholder=" " />
                    <label for="harga" class="absolute text-sm text-gray-500 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-gray-100 px-2 peer-focus:px-2 peer-focus:text-cyan-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">Harga</label>
                </div>
                <div class="relative mr-2">
                            
                            
                    {{-- <label class="block mb-2 text-sm font-medium text-gray-900 " for="file_input">Foto</label> --}}
                    <input class="block w-full text-sm text-gray-500 border border-gray-300 rounded-lg cursor-pointer bg-transparent bg-cyan-700" aria-describedby="file_input_help" id="file_input" name="gambar" type="file">
                    {{-- <p class="mt-1 text-sm text-gray-500 " id="file_input_help">SVG, PNG, JPG or GIF (MAX. 800x400px).</p> --}}

                </div>
                <button type="submit" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2">Simpan</button>
            </form>

            
        </div>
        <table class="w-full text-sm text-left text-gray-500">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50">
                <tr>
                    <th scope="col" class="w-1 px-6 py-3">
                        No
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Nama
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Harga
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Aksi
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach ($foods as $food)
                <tr class="bg-white border-b">
                    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                        {{$loop->iteration }}
                    </th>
                    <td class="px-6 py-4">
                        {{$food->nama}}
                    </td>
                    <td class="px-6 py-4">
                        {{$food->harga}}
                    </td>
                    <td class="px-6 py-4 flex space-x-2">
                        <div>
                            <a href="{{route('food.edit', $food->id)}}">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2"
                                    stroke="currentColor" class="w-6 h-6 text-cyan-500">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                        d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                                </svg>
                            </a>
                        </div>
                        

                       
                        <form action="{{ route('food.destroy', $food->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button title="Hapus" data-modal-target="confirmation-modal" data-modal-show="confirmation-modal">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2"
                                    stroke="currentColor" class="w-6 h-6 text-red-500">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                        d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                                </svg>
                            </button>
                        </form>

                        <a href="{{ asset('storage/' . $food->gambar) }}" target="_blank" title="Gambar" type="button">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                stroke-width="2" stroke="currentColor" class="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round"
                                    d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m5.231 13.481L15 17.25m-4.5-15H5.625c-.621 0-1.125.504-1.125 1.125v16.5c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9zm3.75 11.625a2.625 2.625 0 11-5.25 0 2.625 2.625 0 015.25 0z" />
                            </svg>

                        </a>
                    </td>
                </tr>
                @endforeach
                    
            </tbody>
        </table>
    </div>

   
</body>


<script>

</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js"></script>
</html>